# Generated by Django 3.2.9 on 2021-11-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/2021/13/14')),
                ('job_description', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('availability', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=30)),
                ('duration', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('Contract', 'Contract'), ('Permanent', 'Permanent')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
                ('skill1', models.CharField(blank=True, max_length=50, null=True)),
                ('skill1_experience_year', models.IntegerField(default=0)),
                ('skill2', models.CharField(blank=True, max_length=50, null=True)),
                ('skill2_experience_year', models.IntegerField(default=0)),
                ('skill3', models.CharField(blank=True, max_length=50, null=True)),
                ('skill3_experience_year', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('International Students', 'International Students'), ('PR / Citizen', 'PR / Citizen')], max_length=30)),
                ('availability', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=30)),
                ('resume', models.FileField(upload_to='', verbose_name='resume/2021/13/14')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employer')),
            ],
        ),
    ]
