# Generated by Django 3.2.9 on 2021-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='resume',
            field=models.FileField(upload_to='resume/2021/24/14'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(upload_to='logo/2021/24/14'),
        ),
    ]
