# Generated by Django 3.2.9 on 2021-11-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_job_id_employees_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='skill1_experience_year',
            new_name='experience_year',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='skill1',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='skill2_experience_year',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='skill3_experience_year',
        ),
    ]
