# Generated by Django 3.2.9 on 2021-12-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_employer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='resume',
            field=models.FileField(upload_to='resume/2021/12/29'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(upload_to='logo/2021/12/29'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_year', models.IntegerField(default=0)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employees')),
            ],
            options={
                'db_table': 'Skills',
            },
        ),
    ]
